import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Brain, Calendar, TrendingUp, Target, Timer, Users } from "lucide-react";

const features = [
  {
    icon: Brain,
    title: "AI Training Plans",
    description: "Personalized training plans generated by AI based on your goals, fitness level, and schedule.",
    color: "text-primary"
  },
  {
    icon: Calendar,
    title: "Smart Scheduling",
    description: "Adaptive calendar that adjusts workouts based on your performance and recovery needs.",
    color: "text-sport-swim"
  },
  {
    icon: TrendingUp,
    title: "Progress Analytics",
    description: "Track your fitness trends, training stress, and performance metrics with detailed insights.",
    color: "text-sport-bike"
  },
  {
    icon: Target,
    title: "Race Planning",
    description: "Strategic race day plans with pacing, nutrition, and transition strategies.",
    color: "text-sport-run"
  },
  {
    icon: Timer,
    title: "Workout Logging",
    description: "Quick and easy workout logging with automatic sync from popular fitness devices.",
    color: "text-secondary"
  },
  {
    icon: Users,
    title: "Coach Access",
    description: "Connect with certified coaches for personalized guidance and plan adjustments.",
    color: "text-sport-strength"
  }
];

const FeatureSection = () => {
  return (
    <section id="features" className="py-16 sm:py-24">
      <div className="container mx-auto px-4">
        <div className="text-center mb-16">
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl text-foreground mb-4">
            Everything You Need to Excel
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Comprehensive tools designed specifically for triathlon training, 
            from beginner to Ironman level.
          </p>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
          {features.map((feature, index) => {
            const Icon = feature.icon;
            return (
              <Card key={index} className="group hover:shadow-primary transition-all duration-300 hover:-translate-y-1">
                <CardHeader>
                  <div className={`w-12 h-12 rounded-lg bg-muted flex items-center justify-center mb-4 group-hover:bg-accent transition-colors`}>
                    <Icon className={`h-6 w-6 ${feature.color}`} />
                  </div>
                  <CardTitle className="text-xl">{feature.title}</CardTitle>
                </CardHeader>
                <CardContent>
                  <CardDescription className="text-base">
                    {feature.description}
                  </CardDescription>
                </CardContent>
              </Card>
            );
          })}
        </div>
      </div>
    </section>
  );
};

export default FeatureSection;