// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwzohvwhdquxvnixlzfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3em9odndoZHF1eHZuaXhsemZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1Nzg1ODIsImV4cCI6MjA3NDE1NDU4Mn0.xJ3q9yvabhuigrc1uHuitzd9yEEKFczI0G1v6-WoJfA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});